// Data-driven MVP Buildings Content Table for STARLESS ASCENDANT
// Highest professional practice: modular, scalable, maintainable
import { Building } from './mvpModels';

export const buildingsTable: Building[] = [
  {
    id: 'BLD_001',
    name: 'Command Nexus',
    role: 'Central progression gate',
    effect: 'Increases max level of all other buildings; unlocks sectors & tech tiers',
    maxLevel: 10,
    baseCost: { Energy: 100, Alloy: 50 },
    baseTime: 60,
    scaling: { cost: 1.25, time: 1.3 },
    dependencies: [],
  },
  {
    id: 'BLD_002',
    name: 'Mining Drones Hub',
    role: 'Generates Energy & Alloy',
    effect: '+Energy/min, +Alloy/min',
    maxLevel: 10,
    baseCost: { Energy: 80 },
    baseTime: 30,
    scaling: { cost: 1.2, time: 1.25 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_003',
    name: 'Data Array',
    role: 'Generates Data (research currency)',
    effect: '+Data/min',
    maxLevel: 10,
    baseCost: { Energy: 60, Alloy: 20 },
    baseTime: 45,
    scaling: { cost: 1.2, time: 1.25 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_004',
    name: 'Credit Exchange',
    role: 'Generates Credits (soft currency)',
    effect: '+Credits/min',
    maxLevel: 10,
    baseCost: { Energy: 50 },
    baseTime: 30,
    scaling: { cost: 1.2, time: 1.25 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_005',
    name: 'Research Lab',
    role: 'Unlocks tech tiers; speeds up research',
    effect: '+Research speed %, unlocks Tier 1–5 tech',
    maxLevel: 10,
    baseCost: { Energy: 120, Alloy: 40 },
    baseTime: 90,
    scaling: { cost: 1.25, time: 1.3 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_006',
    name: 'Shipyard',
    role: 'Builds ships; unlocks ship classes; increases fleet capacity',
    effect: '+Ship build speed, unlocks Fighters → Dreadnoughts',
    maxLevel: 10,
    baseCost: { Energy: 150, Alloy: 60 },
    baseTime: 120,
    scaling: { cost: 1.25, time: 1.3 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_007',
    name: 'Orbital Foundry',
    role: 'Gear crafting (basic in MVP)',
    effect: 'Unlocks basic gear tiers',
    maxLevel: 10,
    baseCost: { Energy: 100, Alloy: 30 },
    baseTime: 60,
    scaling: { cost: 1.2, time: 1.25 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_008',
    name: 'Warp Gate',
    role: 'Unlocks sectors & missions',
    effect: 'Access to Sector 1–10; increases daily mission limit',
    maxLevel: 10,
    baseCost: { Energy: 200, Alloy: 50 },
    baseTime: 120,
    scaling: { cost: 1.25, time: 1.3 },
    dependencies: ['BLD_001'],
  },
  {
    id: 'BLD_009',
    name: 'Storage Arrays',
    role: 'Increases resource caps',
    effect: '+Max Energy, Alloy, Data, Credits',
    maxLevel: 10,
    baseCost: { Energy: 40 },
    baseTime: 20,
    scaling: { cost: 1.2, time: 1.25 },
    dependencies: ['BLD_001'],
  },
];
